### ISSUE TITLE
You are still violating rs/zerolog license

### ISSUE THREAD

**Issue by tv42** [z0mbie42/rz-go#16]
You've known about this for at least 4 months: https://www.reddit.com/r/golang/comments/ao3m4j/ripzap_the_fastest_structured_leveled_json_logger/efyzfou/

This repo still shows no signs of containing @rs's copyright.

The code is *clearly* copied:

https://github.com/rs/zerolog/blob/e0f8de6c359435b241b622af8e9a2e6d5a5e012c/array.go  
https://github.com/z0mbie42/rz-go/blob/fdcaa7c230b49d2d72fd87fb3e2d41f822a3db49/array.go

All you need to do is include https://github.com/rs/zerolog/blob/master/LICENSE in your repo. Do the right thing.

**Comment by rs** [comment]
Thanks for the heads up @tv42.

@z0mbie42 I see that you mentioned the original project in the readme. My understanding of MIT is that you should keep the original LICENSE file with the attribution. You can then attribute different parts of the projects to the different authors like:

> Copyright for portions of project Foo are held by [original author, year] as part of project Bar. All other copyright for project Foo are held by [your name, year].

(explanation found [here](https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at))

Also, if you improved zerolog's performance, it would be appreciated to contribute back to the project with a PR.

**Comment by rs** [comment]
I added rz to [logbench](http://hackemist.com/logbench/). For the record, rz is losing on zerolog on every tests, which make sense as your API has to suffer the allocation of the variadic slice.

**Comment by rs** [comment]
Your bench are biased BTW, you pre-compute your fields: https://github.com/z0mbie42/rz-go/blob/master/benchmarks/log_test.go#L332.

**Comment by z0mbie42** [comment]
Hi @rs, thank you for the clarification about the license thing, because with all the drama and the internet "lawyers", I wasn't sure what is the right thing to do (none of them clearly proved what is required by the MIT, but throwed up their opinion instead). I will happily comply within the day.


Regarding the PR, to be clear `rz` started at some micro changes (optimization ? I don't remember clearly) of `zerolog` but then the API was completely changed to remove the `.Msg` 'unsafe' thing, so I thought it was late for a PR.


Regarding the performance I will study of anything is wrong, and correct when appropriate :)

**Comment by z0mbie42** [comment]
@tv42 if something is not done in time it's either because I don't have the bandwidth to take care of it, either because I do not understand the problem/solutions clearly.

So next time a PR with explanations is preferred  rather than pointing finger 😃

**Comment by tv42** [comment]
The license literally says what to do: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

No information here was new, you knew all this 4 months ago. See reddit.
